org.gradle.jvmargs=-Xmx3G -Dfile.encoding=GBK -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=customnpcs_ysm_compat
mod_name=CustomNPCs YSM Compat
mod_license=GNU General Public License v3.0
mod_version=0.2.0
mod_group_id=com.arxyt.customnpcsysmcompat
mod_authors=arxyt
mod_description=Animated Yes Steve Model support for CustomNPCs.
